### ISSUE TITLE
register.js:85 Uncaught (in promise) Error

### ISSUE THREAD

**Issue by ektek** [o15y/staart-ui#177] opened 2019-08-30 10:10 UTC
Validation errors from the backend are not handled right now.

Frontend:
```
:8080/v1/auth/register:1 POST http://localhost:8080/v1/auth/register 500 (Internal Server Error)
register.js:85 Uncaught (in promise) Error: Error: Request failed with status code 500
    at register.js:85
```

Backend:
```
Error: joi:{"isJoi":true,"name":"ValidationError","details":[{"message":"\"name\" with value \"Anon Test1\" fails to match the required pattern: /^[a-zA-Z ]*$/","path":["name"],"type":"string.regex.base","context":{"pattern":{},"value":"anon Test1","key":"name","label":"name"}}],"_object":{"email":"ek@anon.app","name":"anon Test1","password":"testing123"}}
    at Object.exports.joiValidate (/home/anon/development/staart/dist/src/helpers/utils.js:144:15)
    at /home/anon/development/staart/dist/src/helpers/middleware.js:190:17
    at Layer.handle [as handle_request] (/home/anon/development/staart/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/anon/development/staart/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/anon/development/staart/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/anon/development/staart/node_modules/express/lib/router/layer.js:95:5)
    at /home/anon/development/staart/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/anon/development/staart/node_modules/express/lib/router/index.js:335:12)
    at next (/home/anon/development/staart/node_modules/express/lib/router/index.js:275:10)
    at module.exports.<anonymous> (/home/anon/development/staart/node_modules/express-brute/index.js:142:36)
```

**Comment by AnandChowdhary** [comment] 2019-08-30 10:21
This is super weird, because when I try it on https://staart-demo.o15y.com/auth/register/, I got an HTTP `422` with a half-decent message.

I'll have a closer look.

**Comment by AnandChowdhary** [comment] 2019-08-30 10:22
JSYK, you get a `500` when we didn't handle the error "naturally" using the `errors.ts` middleware file. The `{ "isJoi": true }` in your error is supposed to tell Staart to handle it as a Joi error and send an HTTP `422` with the message.

**Comment by ektek** [comment] 2019-08-30 10:31
I am getting the same on email verification:

```
runtime.js:833 Uncaught (in promise) ChunkLoadError: Loading chunk pages/auth/2fa.pages/auth/forgot.pages/auth/login.pages/auth/recover.pages/auth/refresh.pages/auth/register failed.
(timeout: http://localhost:3000/_nuxt/pages/auth/2fa.pages/auth/forgot.pages/auth/login.pages/auth/recover.pages/auth/refresh.pages/auth/register.js)
    at Function.requireEnsure [as e] (http://localhost:3000/_nuxt/runtime.js:833:26)
    at Function.fn.e (http://localhost:3000/_nuxt/runtime.js:177:40)
    at _22babaa2 (http://localhost:3000/_nuxt/app.js:2802:275)
    at VueComponent.prefetch (http://localhost:3000/_nuxt/app.js:2032:36)
    at http://localhost:3000/_nuxt/app.js:1961:10
    at Array.forEach (<anonymous>)
    at IntersectionObserver.push../.nuxt/components/nuxt-link.client.js.observer (http://localhost:3000/_nuxt/app.js:1953:11)
```

Looks like a middleware issue, maybe specific to localhost?

**Comment by AnandChowdhary** [comment] 2019-08-30 10:35
This one is just saying Nuxt wasn't able to load the route. This looks like it's a `staart-ui` issue and not the backend. I'll try to clone and install UI from scratch and see if I can reproduce it.

**Comment by ektek** [comment] 2019-08-30 10:48
Minor, but to be aware when debugging, this is hardcoded: https://github.com/o15y/staart-ui/blob/master/nuxt.config.ts#L90

**Comment by ektek** [comment] 2019-09-05 07:06
@AnandChowdhary did you ever manage to replicate this?

**Comment by AnandChowdhary** [comment] 2019-09-05 07:27
Hi @ektek, can you please confirm whether your build script says `nuxt` or `nuxt-ts`? If you're still on the older version, I think `master` should be working now.

```bash
git pull git@github.com:o15y/staart-ui
```

**Comment by AnandChowdhary** [comment] 2019-10-25 19:27
@ektek, since I wasn't able to reproduce this issue and I'm hoping it should be working for you now, I'm closing now. You can open a new issue if you face this again.

**Closed by AnandChowdhary** 2019-10-25 19:27 UTC
Labels: bug
